### ISSUE TITLE
missing ip family

### ISSUE THREAD

**Issue by tushar-ty** [prsunny/msft-code#4]
https://github.com/prsunny/msft-code/blob/1bff7064bb5f1577bda26398b603dd0f16815c58/src/sai_vxlan.cpp#L204

Should be:
next_hop_attr.value.ipaddr.addr.ip4 = host_ip;
next_hop_attr.value.ipaddr.addr_family = SAI_IP_ADDR_FAMILY_IPV4;

**Comment by prsunny** [comment]
Fixed. Pushed the changes!
